import Head from "next/head";
import Image from "next/image";
import Page_Main from "./main";
// import { Inter } from "@next/font/google";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>소중함</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page_Main />
    </>
  );
}
